services:
  - type: web
    name: college-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn backend_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend_project.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: render.com
