services:
  - type: web
    name: django-backend
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend_project.settings
      - key: PYTHON_VERSION
        value: 3.11
