# Generated by Django 5.2.4 on 2025-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
